import{a as P,S,i as l}from"./assets/vendor-DUzvakyU.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const j={key:"49359598-9a4c243d7cce225cafe13dd3f",image_type:"photo",per_page:15,orientation:"horizontal",safesearch:"true"};async function f(e,r){return await P.get("https://pixabay.com/api/",{params:{page:r,q:e,...j}})}const p=document.querySelector(".gallery"),q=new S(".gallery-link");function x(e){const r=e.map(o=>{const{webformatURL:d,largeImageURL:t,tags:s,likes:i,views:v,comments:b,downloads:w}=o;return`<li class="gallery-item">
            <a  class='gallery-link' href="${t}"><img class="item-image" src="${d}" alt="${s}"></a>
                <ul class = 'image-info'>
                    <li>
                        <p class="item-likes"><span class="info-accent">Likes</span>${i}</p>
                    </li>
                    <li>
                        <p class="item-views"><span class="info-accent">Views</span>${v}</p>
                    </li>
                    <li>
                        <p class="item-comments"><span class="info-accent">Comments</span>${b}</p>
                    </li>
                    <li>
                        <p class="item-downloads"><span class="info-accent">Downloads</span>${w}</p>
                    </li>
                </ul>
        </li>`}).join("");p.insertAdjacentHTML("beforeend",r),q.refresh()}function F(){p.innerHTML=""}const g=document.querySelector(".gallery"),m=document.querySelector(".form"),c=document.querySelector(".loader"),$=document.querySelector(".container"),a=document.querySelector(".load-more-button");let n="",y=0,u=1;m.addEventListener("submit",async e=>{if(e.preventDefault(),n=e.currentTarget.elements.searchText.value.trim(),!!O(n)){u=1,c.classList.remove("js-hidden"),a.classList.add("js-hidden");try{const r=await f(n,u);y=r.data.totalHits;const o=r.data.hits;F(),h(o),L(n)}catch{l.info({message:"Sorry, we have a problems, try later"})}}});function O(e){return e===""?(l.error({title:"Error",message:"Please, input data to search."}),!1):!0}function h(e){if(!T(e)){c.classList.add("js-hidden"),m.reset();return}x(e),D(),c.classList.add("js-hidden"),$.classList.remove("center"),m.reset()}function T(e){return e.length===0?(l.error({message:"Sorry, there are no images matching your search query. Please try again!"}),!1):!0}function D(){g.children.length<y?a.classList.remove("js-hidden"):(a.classList.add("js-hidden"),l.error({message:"We`re sorry, but you`ve reached the end of search results."}))}a.addEventListener("click",async()=>{L(n)});async function L(e){u+=1,a.classList.add("js-hidden"),c.classList.remove("js-hidden");try{const r=(await f(e,u)).data.hits;h(r),H(),a.classList.remove("js-hidden"),c.classList.add("js-hidden")}catch{l.info({message:"Sorry, we have a problems, try later"})}}function H(){const e=g.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:2*r,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
