import{a as b,S as w,i as l}from"./assets/vendor-DUzvakyU.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const j={key:"49359598-9a4c243d7cce225cafe13dd3f",image_type:"photo",per_page:15,orientation:"horizontal",safesearch:"true"};function f(e,s){return b.get("https://pixabay.com/api/",{params:{page:s,q:e,...j}})}const P=document.querySelector(".gallery");function S(e){const s=e.map(i=>{const{webformatURL:t,largeImageURL:r,tags:c,likes:g,views:y,comments:L,downloads:v}=i;return`<li class="gallery-item">
            <a href="${r}"><img class="item-image" src="${t}" alt="${c}"></a>
                <ul class = 'image-info'>
                    <li>
                        <p class="item-likes"><span class="info-accent">Likes</span>${g}</p>
                    </li>
                    <li>
                        <p class="item-views"><span class="info-accent">Views</span>${y}</p>
                    </li>
                    <li>
                        <p class="item-comments"><span class="info-accent">Comments</span>${L}</p>
                    </li>
                    <li>
                        <p class="item-downloads"><span class="info-accent">Downloads</span>${v}</p>
                    </li>
                </ul>
        </li>`}).join("");P.insertAdjacentHTML("beforeend",s),new w(".gallery a").refresh()}const m=document.querySelector(".gallery"),u=document.querySelector(".form"),n=document.querySelector(".loader"),q=document.querySelector(".container"),a=document.querySelector(".load-more-button");let p,d=1;a.classList.add("js-hidden");n.classList.add("js-hidden");u.addEventListener("submit",async e=>{e.preventDefault();const s=e.currentTarget.elements.searchText.value.trim();if(x(s)){d=1,n.classList.remove("js-hidden"),a.classList.add("js-hidden");try{m.innerHTML="";const o=await f(s,d);p=o.data.totalHits;const i=o.data.hits;h(i),O(s)}catch{l.info({message:"Sorry, we have a problems, try later"})}}});function x(e){return e===""?(l.error({title:"Error",message:"Please, input data to search."}),!1):!0}function h(e){if(!F(e)){n.classList.add("js-hidden"),u.reset();return}S(e),$(),n.classList.add("js-hidden"),q.classList.remove("center"),u.reset(),T()}function F(e){return e.length===0?(l.error({message:"Sorry, there are no images matching your search query. Please try again!"}),!1):!0}function $(){m.children.length<p?a.classList.remove("js-hidden"):(a.classList.add("js-hidden"),l.error({message:"We`re sorry, but you`ve reached the end of search results."}))}function O(e){a.addEventListener("click",async()=>{d+=1,a.classList.add("js-hidden"),n.classList.remove("js-hidden");try{const s=(await f(e,d)).data.hits;h(s),a.classList.remove("js-hidden"),n.classList.add("js-hidden")}catch{l.info({message:"Sorry, we have a problems, try later"})}})}function T(){const e=m.querySelector(".gallery-item");if(e){const s=e.getBoundingClientRect().height;window.scrollBy({top:2*s,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
